export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS";
export const SEARCH_PRODUCTS_ERROR = "SEARCH_PRODUCTS_ERROR";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const ADD_PROJECTS_SUCCESS = "ADD_PROJECTS_SUCCESS";
export const ADD_PROJECTS_ERROR = "ADD_PROJECTS_ERROR";

export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";

export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR";

export const GET_ALL_PROJECT_SUCCESS = "GET_ALL_PROJECT_SUCCESS";
export const GET_ALL_PROJECT_ERROR = "GET_ALL_PROJECT_ERROR";

export const GET_COMPLETED_PROJECTS_SUCCESS = "GET_COMPLETED_PROJECTS_SUCCESS";
export const GET_COMPLETED_PROJECTS_ERROR = "GET_COMPLETED_PROJECTS_ERROR";
export const GET_TOTAL_COMPLETED_PROJECTS_SUCCESS =
  "GET_TOTAL_COMPLETED_PROJECTS_SUCCESS";
export const GET_TOTAL_COMPLETED_PROJECTS_ERROR =
  "GET_TOTAL_COMPLETED_PROJECTS_ERROR";

export const GET_CLIENT_PROJECTS_SUCCESS = "GET_CLIENT_PROJECTS_SUCCESS";
export const GET_CLIENT_PROJECTS_ERROR = "GET_CLIENT_PROJECTS_ERROR";
export const GET_COMPLETED_CLIENT_PROJECTS_SUCCESS =
  "GET_COMPLETED_CLIENT_PROJECTS_SUCCESS";
export const GET_COMPLETED_CLIENT_PROJECTS_ERROR =
  "GET_COMPLETED_CLIENT_PROJECTS_ERROR";

export const SAVE_ITEM_TO_PROJECT_SUCCESS = "SAVE_ITEM_TO_PROJECT_SUCCESS";
export const SAVE_ITEM_TO_PROJECT_ERROR = "SAVE_ITEM_TO_PROJECT_ERROR";

export const REMOVE_ITEM_TO_PROJECT_SUCCESS = "REMOVE_ITEM_TO_PROJECT_SUCCESS";
export const REMOVE_ITEM_TO_PROJECT_ERROR = "REMOVE_ITEM_TO_PROJECT_ERROR";

export const GET_SAVED_ITEMS_SUCCESS = "GET_SAVED_ITEMS_SUCCESS";
export const GET_SAVED_ITEMS_ERROR = "GET_SAVED_ITEMS_ERROR";
export const GET_LIKED_ITEMS_SUCCESS = "GET_LIKED_ITEMS_SUCCESS";
export const GET_LIKED_ITEMS_ERROR = "GET_LIKED_ITEMS_ERROR";
export const GET_PASSED_ITEMS_SUCCESS = "GET_PASSED_ITEMS_SUCCESS";
export const GET_PASSED_ITEMS_ERROR = "GET_PASSED_ITEMS_ERROR";

export const LIKE_ITEMS_SUCCESS = "LIKE_ITEMS_SUCCESS";
export const LIKE_ITEMS_ERROR = "LIKE_ITEMS_ERROR";

export const PASS_ITEMS_SUCCESS = "PASS_ITEMS_SUCCESS";
export const PASS_ITEMS_ERROR = "PASS_ITEMS_ERROR";

export const UPLOAD_PRODUCT_CSV_SUCCESS = "UPLOAD_PRODUCT_CSV_SUCCESS";
export const UPLOAD_PRODUCT_CSV_ERROR = "UPLOAD_PRODUCT_CSV_ERROR";

export const UPLOAD_INVENTORY_CSV_SUCCESS = "UPLOAD_INVENTORY_CSV_SUCCESS";
export const UPLOAD_INVENTORY_CSV_ERROR = "UPLOAD_INVENTORY_CSV_ERROR";

export const GET_DESIGNER_SUCCESS = "GET_DESIGNER_SUCCESS";
export const GET_DESIGNER_ERROR = "GET_DESIGNER_ERROR";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const GET_CART_ITEM_SUCCESS = "GET_CART_ITEM_SUCCESS";
export const GET_CART_ITEM_ERROR = "GET_CART_ITEM_ERROR";

export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_ERROR = "GET_CART_ITEMS_ERROR";

export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS";
export const UPDATE_QUANTITY_ERROR = "UPDATE_QUANTITY_ERROR";

export const UPDATE_PROJECT_STATUS_SUCCESS = "UPDATE_PROJECT_STATUS_SUCCESS";
export const UPDATE_PROJECT_STATUS_ERROR = "UPDATE_PROJECT_STATUS_ERROR";

export const GET_PROJECTS_WITH_SAVED_ITEM_SUCCESS =
  "GET_PROJECTS_WITH_SAVED_ITEM_SUCCESS";
export const GET_PROJECTS_WITH_SAVED_ITEM_ERROR =
  "GET_PROJECTS_WITH_SAVED_ITEM_ERROR";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_ERROR = "PAYMENT_ERROR";

export const CHANGE_PAID_STATUS_SUCCESS = "CHANGE_PAID_STATUS_SUCCESS";
export const CHANGE_PAID_STATUS_ERROR = "CHANGE_PAID_STATUS_ERROR";

export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_ERROR = "CONTACT_US_ERROR";

export const BUSINESS_EMAIL_SUCCESS = "BUSINESS_EMAIL_SUCCESS";
export const BUSINESS_EMAIL_ERROR = "BUSINESS_EMAIL_ERROR";

export const AFFIRM_PAYMENT_SUCCESS = "AFFIRM_PAYMENT_SUCCESS";
export const AFFIRM_PAYMENT_ERROR = "AFFIRM_PAYMENT_ERROR";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_TAXES_SUCCESS = "GET_TAXES_SUCCESS";
export const GET_TAXES_ERROR = "GET_TAXES_ERROR";

export const ADD_COMMISSION_SUCCESS = "ADD_COMMISSION_SUCCESS";
export const ADD_COMMISSION_ERROR = "ADD_COMMISSION_ERROR";

export const GET_PAST_ORDERS_SUCCESS = "GET_PAST_ORDERS_SUCCESS";
export const GET_PAST_ORDERS_ERROR = "GET_PAST_ORDERS_ERROR";

export const GET_TOTAL_DESIGNER_SUCCESS = "GET_TOTAL_DESIGNER_SUCCESS";
export const GET_TOTAL_DESIGNER_ERROR = "GET_TOTAL_DESIGNER_ERROR";

export const AVERAGE_NEW_PROJECTS_PER_DESIGNER_SUCCESS =
  "AVERAGE_NEW_PROJECTS_PER_DESIGNER_SUCCESS";
export const AVERAGE_NEW_PROJECTS_PER_DESIGNER_ERROR =
  "AVERAGE_NEW_PROJECTS_PER_DESIGNER_ERROR";

export const SAVED_ITEMS_PER_PROJECT_SUCCESS =
  "SAVED_ITEMS_PER_PROJECT_SUCCESS";
export const SAVED_ITEMS_PER_PROJECT_ERROR = "SAVED_ITEMS_PER_PROJECT_ERROR";

export const PER_DESIGNER_PURCHASE_SUCCESS = "PER_DESIGNER_PURCHASE_SUCCESS";
export const PER_DESIGNER_PURCHASE_ERROR = "PER_DESIGNER_PURCHASE_ERROR";

export const PER_PROJECT_PURCHASE_SUCCESS = "PER_PROJECT_PURCHASE_SUCCESS";
export const PER_PROJECT_PURCHASE_ERROR = "PER_PROJECT_PURCHASE_ERROR";

export const SPEND_PER_DESIGNER_SUCCESS = "SPEND_PER_DESIGNER_SUCCESS";
export const SPEND_PER_DESIGNER_ERROR = "SPEND_PER_DESIGNER_ERROR";

export const TOTAL_DESIGNERS_BY_TIMERANGE_SUCCESS =
  "TOTAL_DESIGNERS_BY_TIMERANGE_SUCCESS";
export const TOTAL_DESIGNERS_BY_TIMERANGE_ERROR =
  "TOTAL_DESIGNERS_BY_TIMERANGE_ERROR";

export const TOTAL_PROJECTS_BY_TIMERANGE_SUCCESS =
  "TOTAL_PROJECTS_BY_TIMERANGE_SUCCESS";
export const TOTAL_PROJECTS_BY_TIMERANGE_ERROR =
  "TOTAL_PROJECTS_BY_TIMERANGE_ERROR";
